version: '3.8'

services:
  some-postgres:
    image: postgres
    container_name: query-db
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
