spring:
 application:
  name: query-kafka-api


 datasource:
   url: jdbc:postgresql://localhost:5432/querydb
   username: root
   password: password
   driver-class-name: org.postgresql.Driver
   
 jpa:
  hibernate:
   ddl-auto: update  
  show-sql: true
  properties:
   hibernate:
    format_sql: true
  database: postgresql 
  database-platform: org.hibernate.dialect.PostgreSLDialect
  
 kafka:
  template:
    default-topic: student-topic
  consumer:
   bootstrap-servers: localhost:9092
   group-id: student-group1
   auto-offset-reset: earliest
   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      
  #Kafka can deserialize all the classes from this package
  properties:
   spring:
    json:
     trusted:
      packages: org.miaoubich.event
