spring:
 application:
  name: query-kafka-api


 datasource:
   url: jdbc:postgresql://localhost:5432/querydb
   username: root
   password: password
   driver-class-name: org.postgresql.Driver
   
 jpa:
  hibernate:
   ddl-auto: update  
  show-sql: true
  properties:
   hibernate:
    format_sql: true
  database: postgresql 
  database-platform: org.hibernate.dialect.PostgreSLDialect
